### ISSUE TITLE
What's the resolution input format?

### ISSUE THREAD

**Issue by Giorat** [hjwdzh/QuadriFlow#18]
The parameter -f [resolution] isn't explained in the readme.

Is resolution the numbero of vertices? Faces? Is it a vertex decimation scale?

You could add a simple example in the readme to explain better what you intend for resolution.

Thank you very much, Riccardo.

**Comment by hjwdzh** [comment]
It is the number of faces. I will fix it in the readme.

**Comment by Giorat** [comment]
Still not fixed in the Readme
