### ISSUE TITLE
Meshing a simple plate with a hole in 2D is an issue!!

### ISSUE THREAD

**Issue by brennanOnTheMoor** [hjwdzh/QuadriFlow#19]
Meshing the [Gargoyle](https://github.com/hjwdzh/QuadriFlow/blob/master/examples/Gargoyle_input.obj) model was very impressive... but why can I not mesh a simple square plate with a hole in 2D? If you can mesh a Gargoyle surely you should be able to mesh this very simple model?

I have attached an example of a 2D quad mesh on this model below to describe what I would like to see. I was hoping QuadriFlow could generate a better mesh on this example.

**Triangular Input Mesh (.OBJ File)**
![plate_with_hole_sheet](https://user-images.githubusercontent.com/42972451/45041066-576dde80-b05f-11e8-98a4-e0222eb8d954.png)

**My Quad Mesh (hoping QuadriFlow would do something better...)**
![plate_with_hole_mesh_2d](https://user-images.githubusercontent.com/42972451/45040623-5b4d3100-b05e-11e8-9ad1-133b113839db.PNG)

Certainly with the manifold "work-around" QuadriFlow produces a mesh on an enclosed volume but not a 2D mesh.

**QuadriFlow Mesh with Manifold Work-Around (not desired)**
![plate_with_hole_manifold](https://user-images.githubusercontent.com/42972451/45041279-c8ad9180-b05f-11e8-8ca1-de46dc53967a.png)

Please find the .obj file content pasted below.

~~~shell
# 93 vertex positions
v  0 50 25
v  0 50 0
v  0 34.0483 20.7422
v  0 34.0483 20.7422
v  0 34.8229 23.1262
v  0 50 25
v  0 50 0
v  0 32.7051 18.6258
v  0 34.0483 20.7422
v  0 50 0
v  0 28.6812 15.7022
v  0 30.8779 16.9098
v  0 50 0
v  0 26.2533 15.0789
v  0 28.6812 15.7022
v  0 50 0
v  0 0 0
v  0 23.7467 15.0789
v  0 0 0
v  0 21.3188 15.7022
v  0 23.7467 15.0789
v  0 23.7467 15.0789
v  0 26.2533 15.0789
v  0 50 0
v  0 0 0
v  0 17.2949 18.6258
v  0 19.1221 16.9098
v  0 19.1221 16.9098
v  0 21.3188 15.7022
v  0 0 0
v  0 30.8779 16.9098
v  0 32.7051 18.6258
v  0 50 0
v  0 0 25
v  0 15.1771 23.1262
v  0 15.9517 20.7422
v  0 0 25
v  0 15.0197 25.6279
v  0 15.1771 23.1262
v  0 15.9517 20.7422
v  0 0 0
v  0 0 25
v  0 15.9517 20.7422
v  0 17.2949 18.6258
v  0 0 0
v  0 0 50
v  0 16.5567 30.3583
v  0 15.4894 28.0902
v  0 0 50
v  0 18.1545 32.2897
v  0 16.5567 30.3583
v  0 0 50
v  0 50 50
v  0 25 35
v  0 25 35
v  0 22.5131 34.6858
v  0 0 50
v  0 22.5131 34.6858
v  0 20.1825 33.7631
v  0 0 50
v  0 20.1825 33.7631
v  0 18.1545 32.2897
v  0 0 50
v  0 50 50
v  0 29.8175 33.7631
v  0 27.4869 34.6858
v  0 50 50
v  0 33.4433 30.3583
v  0 31.8455 32.2897
v  0 50 50
v  0 50 25
v  0 34.5106 28.0902
v  0 34.5106 28.0902
v  0 33.4433 30.3583
v  0 50 50
v  0 31.8455 32.2897
v  0 29.8175 33.7631
v  0 50 50
v  0 27.4869 34.6858
v  0 25 35
v  0 50 50
v  0 15.4894 28.0902
v  0 0 25
v  0 0 50
v  0 50 25
v  0 34.9803 25.6279
v  0 34.5106 28.0902
v  0 15.4894 28.0902
v  0 15.0197 25.6279
v  0 0 25
v  0 34.8229 23.1262
v  0 34.9803 25.6279
v  0 50 25

# Mesh with 31 faces
f  1//1 2//2 3//3
f  4//4 5//5 6//6
f  7//7 8//8 9//9
f  10//10 11//11 12//12
f  13//13 14//14 15//15
f  16//16 17//17 18//18
f  19//19 20//20 21//21
f  22//22 23//23 24//24
f  25//25 26//26 27//27
f  28//28 29//29 30//30
f  31//31 32//32 33//33
f  34//34 35//35 36//36
f  37//37 38//38 39//39
f  40//40 41//41 42//42
f  43//43 44//44 45//45
f  46//46 47//47 48//48
f  49//49 50//50 51//51
f  52//52 53//53 54//54
f  55//55 56//56 57//57
f  58//58 59//59 60//60
f  61//61 62//62 63//63
f  64//64 65//65 66//66
f  67//67 68//68 69//69
f  70//70 71//71 72//72
f  73//73 74//74 75//75
f  76//76 77//77 78//78
f  79//79 80//80 81//81
f  82//82 83//83 84//84
f  85//85 86//86 87//87
f  88//88 89//89 90//90
f  91//91 92//92 93//93
~~~

**Comment by hjwdzh** [comment]
Thanks for your comment. I believe I can directly mesh the 2D without a 3D volume. However, since we did not implement the boundary consistent orientation field, we might not preserve the boundary.

**Comment by zhou13** [comment]
You may also want to try sharp preserving heuristic with `-sharp` and see if it works better.

**Comment by brennanOnTheMoor** [comment]
I tried the sharp preserving but it crashed.

Have you an example of how to mesh in 2d without a 3d volume?
