### ISSUE TITLE
Copyleft code in eigen

### ISSUE THREAD

**Issue by zewt** [hjwdzh/QuadriFlow#25]
(Just a question and not a bug report, but GitHub gives no way to send messages to people other than filing a bug.  Feel free to close.)

The code and almost all libraries are under permissive licenses, but Eigen/SparseCholesky is LGPL.  The build fails with -DEIGEN_MPL2_ONLY.  Just wanted to make sure you're aware of it, since it it's a deterrent to using the code and it seems to be the only copyleft dependency.

FYI, it would be helpful to have a clear list of dependencies, since it has a ton of them.  Other than the ones listed in the readme, it's looking for at least "ceres", "lemon", "pcg32" and "pss".

**Comment by zhou13** [comment]
Hi @zewt Thanks for the suggestion.  I will clarify this in the readme.

**Comment by zhou13** [comment]
I updated the README. Now you will be able to get rid of LGPL code with `-DBUILD_FREE_LICENSE=ON` at the expense of a little performance drop. (using SparseLU to replace SparseCholesky).  The code is not well tested so let me know if you have any issues.
