### ISSUE TITLE
Will the be OS release

### ISSUE THREAD

**Issue by schroef** [hjwdzh/QuadriFlow#26]
I bumped into this app to day and was wondering if there gonna be any release builds for other OS's.
I read on a blender artist thread about BakeMyScan that something was coming. But that was back in November.

Im not familiar with Cbuild or any method of compiling. 

I would like to know if an OSX build will be made and if this is version depended on the os status or so.

**Comment by zhou13** [comment]
Hi @schroef Thanks for being interested in our work. I do not have a OSX at hand so probably @hjwdzh could help you.

**Comment by schroef** [comment]
Okay ill hope so :)

**Comment by hjwdzh** [comment]
Hi @schroef, I have upload a osx binary in the bins folder. Hope it can be directly used on your machine. I will close the issue, and please reopen it if it does not work.

**Comment by schroef** [comment]
@hjwdzh ill check it right away

**Comment by schroef** [comment]
Im not sure how to run it, so did try terminal. I get this error about missing dylib

```
/Users/romboutversluijs/Downloads/QuadriFlow-master/bins/quadriflow-osx ; exit;
MBP-Schroef:~ Admin$ /Users/romboutversluijs/Downloads/QuadriFlow-master/bins/quadriflow-osx ; exit;
dyld: Library not loaded: /opt/local/lib/libglpk.36.dylib
  Referenced from: /Users/romboutversluijs/Downloads/QuadriFlow-master/bins/quadriflow-osx
  Reason: image not found
Trace/BPT trap: 5
logout
```

**Comment by schroef** [comment]
Okay i jsut installed brew and im now installing those dependencies. Thats probably my issue here. I also found another OSX build [here](https://3dcoat.com/forum/index.php?/topic/22711-new-quad-auto-retopology-algorithm/&do=findComment&comment=155420)
This gave me a different error though about missing TBB

**Comment by schroef** [comment]
I get all kinds of errors with some of the dependies, i didnt see any for GLPK so i did a brew install glpk. Now i do see a libglpk.40.dylib but thats is a different number than this bin needs?

<img width="436" alt="screen shot 2019-01-27 at 20 05 22" src="https://user-images.githubusercontent.com/6923008/51808802-0e693180-226f-11e9-855f-fd0c9304f791.png">

**Comment by schroef** [comment]
Im on 10.11.6 and i think that is also causing an issue now.

This is what i get when trying to install TBB. SOrry if this is not related to this repo. Imjust trying to figure out how to get it running. Would be nice if this could be a simple app or some executable. What a hustle to get started....

<img width="1440" alt="screen shot 2019-01-27 at 20 07 31" src="https://user-images.githubusercontent.com/6923008/51808810-43758400-226f-11e9-8536-74dceac3bcd1.png">

**Comment by schroef** [comment]
well after installing pythin like 3-4 times and checking what was wrong with brew doctor i got it to work. however its not your bin that works, that still returns that error on that mismatching file.

The attached osx i found in that earlink [link ](https://github.com/hjwdzh/QuadriFlow/issues/26#issuecomment-457963457), that one does work.

PS should this app work on all cores? I see it utilizing just 4 on my macbook pro?

**Comment by schroef** [comment]
PS for that missing file i did a nasty file hack, i simply changed the name from libglpk.40.dylib to libglpk.36.dylib in this folder /usr/local/lib/libglpk.36.dylib

now your bin for osx also works :)

**Comment by zhou13** [comment]
If you have brew installed, it is better just compile the project using the instruction in the `README.md`.  Changing the library with different name may cause potential problems.

**Comment by schroef** [comment]
@zhou13 
Okay perhaps ill should try that. Its quite a big package all together with all those depencies. I noticed that boost lib is 1.3 gb???

**Comment by the-real-tokai** [comment]
The released builds are just broken, IMHO. Such kind of dependencies should be statically linked in such cases, then there are no random external dependencies which most users (not developers) haven't installed anyway. Looking forward to a fixed release. :)

**Comment by schroef** [comment]
Well the weird thing is, the OSX wont run on my OS because im using 10.11.6. But when i use terminal and open it by dropping the macos file inside the app, it simply runs.

**Comment by the-real-tokai** [comment]
That's a known workaround for such cases. Recently dealt with another app which required a newer version of OS X than I have (reported via Finder and a crossed out icon.) Using the binary directly via Terminal worked fine however. Just a way of Apple to force their planned  obsolescence onto the users and developers. In most cases there's no technical reason for doing so, IMHO.

Anyway… back to fixing quadriflow, here's my workaround: fetch the glpk library from  "https://www.gnu.org/software/glpk/", build it with `./configure` + `make` + `make install` which will drop it into "/usr/local/". Now we can inspect the quadriflow binary with `otool -L quadriflow-osx` to see what external libs it wants from where and fix that by using: `install_name_tool -change '/opt/local/lib/libglpk.36.dylib' '/usr/local/lib/libglpk.dylib' quadriflow-osx` which will make it load the missing lib from the new /usr/local location. The slight API versions change from 36 to 40 doesn't seem to be a problem, luckily… all remains compatible. I don't even have an "/opt" path on my system, so this works better for me than installing the glpk lib into a new /opt directory.
