### ISSUE TITLE
Face resolution flag appears to be disregarded

### ISSUE THREAD

**Issue by meder411** [hjwdzh/QuadriFlow#28]
I ran `./quadriflow -i ../../icosphere7.obj -o quadsphere.obj -f 131072` on a order 7 icosphere triangular mesh in hopes of returning a 131,072 face quad mesh and it returned a mesh with 1,076,594 face quad mesh. While the quality is fantastic, it's nearly an order of magnitude higher resolution than I'd asked for. 

I can understand if there cannot be an exact match to the number of faces due to geometric principals, but this seems way off. Am I missing something about the `-f` flag? 

If it helps, I've attached the input I used as [icosphere7.zip](https://github.com/hjwdzh/QuadriFlow/files/2923739/icosphere7.zip) and the output as [quadsphere.zip](https://github.com/hjwdzh/QuadriFlow/files/2923743/quadsphere.zip).

**Comment by meder411** [comment]
There are also some unexpected efffects at the singularities (i.e. the original vertices in the icosahedron). Here is an image of one of them:
![snapshot00](https://user-images.githubusercontent.com/6818607/53702529-ffc5eb00-3dd5-11e9-89c1-9b90a43c8d73.png)

**Comment by hjwdzh** [comment]
Certain Artifacts could exist since we are approximating the original problem instead of solving a global optimal. -f control the scale of the edge length and thus the number of faces. However, it can just give it a linear scale while we cannot control the exact number of faces.
