### ISSUE TITLE
QuadriFlow consistently 10x slower than Instant Meshes on macOS, why?

### ISSUE THREAD

**Issue by bitinn** [hjwdzh/QuadriFlow#31]
Perhaps I am missing something, but my manual benchmark suggests Instant Meshes somehow run much faster (5x-10x) than QuadriFlow:

```
$ time ./instantmeshes -v 2000 -S 2 -d -o test3_output2.obj test3.obj

real	0m2.338s
user	0m4.994s
sys	0m0.198s

$ time ./quadriflow -adaptive -i test3.obj -o test3_output1.obj -f 2000

real	0m23.900s
user	0m22.801s
sys	0m0.883s

$ time ./quadriflow -i test3.obj -o test3_output3.obj -f 2000

real	0m11.733s
user	0m11.051s
sys	0m0.567s
```

`test3.obj` is `3bommes/Buddha_input.obj`, I have ran a few similar tests, on macOS they are consistently slower than Instant Meshes.

In the center is Instant Meshes' result, Left/Right are QuadriFlow's (Right: `-adaptive` enabled; Left: `-adaptive` disabled), all 3 results have tris count at around 15K.

<img width="1082" alt="Screen Shot 2019-05-26 at 21 13 32" src="https://user-images.githubusercontent.com/1484279/58382296-3426fd00-7ffb-11e9-83cf-670cd877546b.png">

<img width="1064" alt="Screen Shot 2019-05-26 at 21 13 25" src="https://user-images.githubusercontent.com/1484279/58382300-3d17ce80-7ffb-11e9-8739-feef5374f733.png">

(`-mcf` and `-sat` flags increases the compute time further, albeit with better results, so I omit them here.)

Is there an obvious reason as to why this contradicts with the paper's test results?

(The key difference here might be that I am on Intel GPU; but CPU speed is comparable.)

**Comment by hjwdzh** [comment]
The released version is purely implemented on the CPU with a single core rather than on the GPU.

**Comment by hjwdzh** [comment]
The released version is purely implemented on the CPU with a single core rather than on the GPU.

**Comment by zhou13** [comment]
QuadriFlow internally calls the procedures in Instant Mesh. So it is expected that it will be slower than IM without GPU acceleration.

**Comment by bitinn** [comment]
Thx both for the explanation.
