### ISSUE TITLE
[Blender] Integrating QuadriFlow in other software and distribution models

### ISSUE THREAD

**Issue by DarkDefender** [hjwdzh/QuadriFlow#32]
Hi!
Thanks to the work by Pablo Dobarro, we are going to integrate QuadriFlow in Blender with other sculpt mode improvements:
https://www.artstation.com/pablodp606/blog/1vEn/new-blender-sculpt-mode-introduction

Now the reason I've opened this issue is that we (the developers at the Blender Institute) are a bit unsure how we should go about the integration. We are going to need to do some slight modifications to the QuadriFlow code to make it able to interface with the internal mesh formats in blender.

However, we could of course like to have our changes merged upstream too. So we wonder if you are willing to accept application specific APIs like this.

In addition to this, we are uncertain how we should include QuadriFlow in the blender project. We have two options:

1. Copy the Quadriflow code base into the blender code base so that users doesn't have to download and install Quadriflow. (This could lead to the code base in blender and the official code drifting apart as it would effectively be a fork)

2. Make Quadriflow a standalone library and include it as a dependency. (Might be a bit unnecessary if it is only blender that would use the library in question)

Do you guys have any thoughts or input?

**Comment by hjwdzh** [comment]
I am very willing that my code could be further developed and make it blender-friendly. That should give it more impact. It seems that the first option will have benefit in the long term, and I prefer that. That means, if you have any questions about the details of the code, please feel free to contact me (jingweih@stanford.edu) and I am willing to answer them when I have time. Thanks a lot for your interest in this project.

**Comment by DarkDefender** [comment]
@hjwdzh just an update:

I've managed to integrate quadriflow into blender (but nothing has been merged to the blender master branch yet).
I did some smaller changes that I've posted here: #36 

I did run into some issues with folds in the output meshes and I have reported that as a separate issue here.

**Comment by hjwdzh** [comment]
@DarkDefender Thanks.
