### ISSUE TITLE
Quadriflow sharp edges issue

### ISSUE THREAD

**Issue by scorpion81** [hjwdzh/QuadriFlow#33]
Hello, 

I have made a simple blender addon which basically invokes the quadriflow.exe (Windows build via MSVC 2017)  via commandline. The selected object is  converted to obj, processed by quadriflow and return as obj, as well as converted back.
My issue with it is now, that it will exit prematurely in "Build Integer Constraints…" if too many "sharp edges" exist (and if "-sharp" is enabled). 

For example, see this input .obj (zipped)
[original.zip](https://github.com/hjwdzh/QuadriFlow/files/3434839/original.zip)
Quadriflow.exe is called like 
`quadriflow.exe -i original.obj -o out.obj -f 500 -sharp`

The addon is here: 
[QuadriflowRemesh.zip](https://github.com/hjwdzh/QuadriFlow/files/3434847/QuadriflowRemesh.zip)

Just install in blender and in the addon preferences, point to a path with the quadriflow executable. 
Then...
![quadriflow_addon](https://user-images.githubusercontent.com/1172149/61937832-007f3980-af90-11e9-95d3-1fc80254198f.png)

and enable "Sharp" in the following popup field and "Start Remeshing".
The original blend file : 
[tower.zip](https://github.com/hjwdzh/QuadriFlow/files/3434889/tower.zip)

**Comment by hjwdzh** [comment]
Sharp feature preservations ('-sharp') are not yet quite robust. There are some fundamental technical changes that should be proposed in the future to handle this issue robustly.
