### ISSUE TITLE
win7 vs2013 eigen-3.2.0 boost1.70

### ISSUE THREAD

**Issue by jonntd** [hjwdzh/QuadriFlow#35]
Error	18	error C2064: term does not evaluate to a function taking 2 arguments	d:\test_plugin\quadriflow-master\eigen3\eigen\src\Core\CoreEvaluators.h	347	1	quadriflow

**Comment by DarkDefender** [comment]
You need a newer eigen version. I would recommend to use the latest 3.3.7 release.

**Comment by hjwdzh** [comment]
@DarkDefender Thanks for helping.
