### ISSUE TITLE
Quadriflow produces folds with certain mesh configurations

### ISSUE THREAD

**Issue by DarkDefender** [hjwdzh/QuadriFlow#37]
It seems like Quadriflow sometimes generates folds in the output mesh:
![quad_prob](https://user-images.githubusercontent.com/312503/63588475-e2b0ee80-c5a6-11e9-8b76-7c3ecb5806cd.png)

I've tried most of the toggle-able features, but none seems to eliminate this.
I will attach a mesh that consistently produces this issue: 
[test_mesh.zip](https://github.com/hjwdzh/QuadriFlow/files/3534118/test_mesh.zip)

This is the command I run to generate the output mesh:
```./quadriflow -i Bruffles.obj -o test.obj```

Is this something that can be fixed or is it an inherent problem with the algorithm?

**Comment by hjwdzh** [comment]
This is an inherent problem of the algorithm, which sometimes cannot remove all the flips. Some other add-on ideas need to be implemented to fix this issue, but not trivial.

**Comment by DarkDefender** [comment]
Can these flips be detected by the algorithm? I'm thinking that we could work around this somewhat by simply applying a smoothing operator on these areas.

**Comment by hjwdzh** [comment]
That's possible. But I think it could be tricky and cannot guarantee robustness. The geometry processing is always tricky:)

**Comment by DarkDefender** [comment]
Right, I was thinking of just having it as a ugly hack in blender until a better solution is found. But for that to work somewhat nicely, I would need the vertex indices of these folds.

Is the possible to get? IE does the algorithm know when it produces these folds?
