### ISSUE TITLE
eigen

### ISSUE THREAD

**Issue by Marco105** [hjwdzh/QuadriFlow#42]
Hello,
I want to try compil with cmake and msg error: FindEigen

**Comment by DarkDefender** [comment]
Do you have the Eigen library installed and working?

**Comment by hjwdzh** [comment]
Are you using linux or mac or windows. In linux, try: sudo apt-get install libeigen3-dev
In mac, try brew install eigen3.

Or you can directly download eigen source files, and specify the path in the cmake.

**Comment by Marco105** [comment]
I'm using W7 and I have DL Eingen source but don't know how to specify it in cmake.
Eingen is currently in the 3rd folder.

**Comment by hjwdzh** [comment]
Maybe you can consider to use the CMake GUI. After you configure it, you can a list of variables and value in the list view. You will be able to find something like an eigen path, you type in the eigen path and re-click configure. Once there is no error, you can create generate to finalize your make or visual studio environment.
