### ISSUE TITLE
Less of an issue and more of a question really.

### ISSUE THREAD

**Issue by RileyGuy** [hjwdzh/QuadriFlow#44]
I'm aware of another similar program called "QuadRemesh" which handles retopology like a beast, but has the caveat of costing 190 dollars or so for a perpetual license. My question is does (or will) this program match that quality? Not to sound entitled or rude or anything lol, but I figured I'd ask.

**Comment by hjwdzh** [comment]
Just have a try.

**Comment by RileyGuy** [comment]
Yeah sorry for making an issue just to ask. But I looked around on the page and I can't find a download for the blender addon anywhere, maybe I'm just blind but could you point me in the right direction?

**Comment by zhou13** [comment]
This is a research project and we don't provide a blender addon. For now you can either compile the executable yourself or uses 3rd addons. See the discussion in https://blenderartists.org/t/quadriflow-remesher/1132946.

Quadriflow will probably be shipped with blender in the near future, see https://developer.blender.org/D5594.
