### ISSUE TITLE
API for fetch source info of new vertices?

### ISSUE THREAD

**Issue by huxingyi** [hjwdzh/QuadriFlow#47]
Hi, QuadriFlow is really nice, I am integrating QuadriFlow to [my modeling tool](https://github.com/huxingyi/dust3d/commit/dd628b6af7f1b425c128fd0ef59a4bada17fa234).

Is there a way to fetch the source vertex please? What I mean is that,
I get the new generated vertex from O_compact, quads from F_compact. But from where does O_compact generated?
For example, there are color and material infos related with old vertex, how to connect the info with the new vertices?
Thanks!

**Comment by hjwdzh** [comment]
It is a good question. One easy solution is to try this link:
https://github.com/libigl/libigl/blob/master/include/igl/point_mesh_squared_distance.h
