### ISSUE TITLE
Only output uniform mesh?

### ISSUE THREAD

**Issue by TangLaoya** [hjwdzh/QuadriFlow#50]
Dear developers,
Thank you very much for your great software. I have a 2-d triangle mesh with multi-scaled size. I used this mesher to convert to quad mesh, however, the output mesh is uniform mesh with many extra nodes added. Is there any command to let the mesher generate high quality but non-uniform meshes?

Thanks,
Tang Laoya
[input.zip](https://github.com/hjwdzh/QuadriFlow/files/7835345/input.zip)

**Comment by TangLaoya** [comment]
In addition, even I put the -sharp option, the output mesh also changed the input boundaries. Could you please help me to take a look at it?

Thanks,
Tang Laoya

**Comment by hjwdzh** [comment]
Currently, we only target to generate uniform mesh. I have not yet solved the problem of boundary or adaptive scale yet. This is a limitation.
