### ISSUE TITLE
Release Build Quadriflow

### ISSUE THREAD

**Issue by jayanam** [hjwdzh/QuadriFlow#52]
Hi, I just built a Release 64 Bit Build for Quadriflow for Windows OS. I would like to use it in my [JRemesh Blender addon](https://github.com/jayanam/jremesh-tools). Is it ok if I upload it to the github in a bin/quadriflow/win64 folder so that the guys can use it? Or do you provide any binaries? Thx and best regards.

**Comment by hjwdzh** [comment]
Sure, you can do it.
